runtime: python27
api_version: 1
threadsafe: yes

env_variables:
  appurl: 'https://storage.googleapis.com/omega-messenger-133010.appspot.com/profile/'
  appurlmail: 'http://omega-messenger-133010.appspot.com/'
  token: 'AIzaSyBRrOaEbGsZsX1u-zZZwtv938C3KIHJZ3A'

libraries:
- name: jinja2
  version: "2.6"
- name: markupsafe
  version: "0.15"
- name: "MySQLdb"
  version: "1.2.5"

handlers:
- url: .*
  script: main.app
  secure: never

beta_settings:
      cloud_sql_instances: "ingrid-application-mysql57"
