runtime: python27
api_version: 1
threadsafe: yes
default_expiration: "1d 1h"

env_variables:
  appurl: 'https://storage.googleapis.com/omega-messenger-133010.appspot.com/profile/'
  appurlmail: 'http://omega-messenger-133010.appspot.com/'
  apptoken: 'AIzaSyBRrOaEbGsZsX1u-zZZwtv938C3KIHJZ3A'
  CLOUDSQL_CONNECTION_NAME: 'ingrid-application:us-central1:ingrid-application-mysql57-instance'
  CLOUDSQL_USER: "dbuser"
  CLOUDSQL_PASSWORD: "MySQL123!"
  CLOUDSQL_SERVER_IP4V: "104.197.138.2"
libraries:
- name: jinja2
  version: "2.6"
- name: markupsafe
  version: "0.15"

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico
- url: .*
  script: main.app
  secure: never
builtins:
- remote_api: on

beta_settings:
      cloud_sql_instances: "ingrid-application:us-central1:ingrid-application-mysql57-instance"
