runtime: python27
api_version: 1
threadsafe: yes

env_variables:
  CLOUDSQL_CONNECTION_NAME: ingrid-application:us-central1:ingrid-application-mysql57
  CLOUDSQL_USER: dbuser
  CLOUDSQL_PASSWORD: MySQL123!
  SWAGGER_FOLDER: "/swagger"

libraries:
- name: MySQLdb
  version: "latest"
- name: jinja2
  version: "2.6"
- name: markupsafe
  version: "0.15"

inbound_services:
- warmup

handlers:
- url: .*
  script: main.app
  secure: never
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico
builtins:
- remote_api: on

beta_settings:
  cloud_sql_instances: "ingrid-application:us-central1:ingrid-application-mysql57"


