version: '3.1'
services:
  # api:
  #   volumes:
  #     - .:/app
  mysql:
    volumes:
      - ./mysql-server/data:/var/lib/mysql:rw
      - ./mysql-server/log:/var/log/mysql:rw
      - ./mysql-server/tmp:/tmp/mysql:rw
