version: '3.1'
services:
  web:
    container_name: wmcp-web
    build:
      context: ../web/
      dockerfile: ./Dockerfile
    links:
      - api
      - adminer
    ports:
      - 8080:8080
  api:
    container_name: wmcp-api
    build:
      context: ../flask/
      dockerfile: ./Dockerfile
    links:
      - mysql
    # env_file: .env.dev
    # entrypoint:
    #   - /bin/bash
    #   - -c
    # command:
    #   - /usr/bin/npm run db:migrate && /usr/bin/npm start
    ports:
      - 8090:8080
    environment:
      - SSH_AUTH_SOCK=/ssh-agent
    volumes:
      - ..:/src
      - $SSH_AUTH_SOCK:/ssh-agent
  mysql:
    container_name: wmcp-mysql
    # image: mysql/mysql-server
    build:
      context: ./mysql-server/
      dockerfile: ./Dockerfile
    restart: always
    entrypoint: ./docker-entrypoint.sh
    command:
      - mysqld
      - --verbose
      - --default-authentication-plugin=mysql_native_password
      - --innodb-use-native-aio=0
      - --innodb-buffer-pool-size=20M
    environment:
      MYSQL_DATABASE: findme
      MYSQL_ROOT_PASSWORD: root
      # MYSQL_ROOT_HOST: 127.0.0.1
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: MySQL123!
    ports:
      - 3306:3306
  adminer:
    container_name: wmcp-adminer
    image: adminer
    restart: always
    ports:
      - 8100:8100
networks:
  default:
    external:
      name: localnet

